<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCoursesRecommendation($company)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.company = '. $company->getId())
            ->setMaxResults(3)
            ->add('orderBy','c.id DESC');

        return $qb->getQuery()
            ->getResult();
    }
}
