<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * ExamAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
