<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * ExamQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
