<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends \Doctrine\ORM\EntityRepository
{
}
