<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * HomeworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeworkRepository extends \Doctrine\ORM\EntityRepository
{
}
