<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewsRecommendation($company)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->where('n.company = '. $company->getId())
            ->setMaxResults(3)
            ->add('orderBy','n.id DESC');

        return $qb->getQuery()
            ->getResult();
    }
}
