<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * QuestionAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
