<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * UserRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
