<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * UserHomeworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHomeworkRepository extends \Doctrine\ORM\EntityRepository
{
}
