<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * UserTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTestRepository extends \Doctrine\ORM\EntityRepository
{
}
