<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * UserCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
