<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * UserExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserExamRepository extends \Doctrine\ORM\EntityRepository
{
}
