<?php

namespace ELearning\CompanyPortalBundle\Repository;

/**
 * UserExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserExamRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActiveExams($exam)
    {
        $qb = $this->createQueryBuilder('ue');
        $qb->where('ue.finished = 1')
            ->andWhere('ue.checked = 0')
            ->andWhere('ue.exam = :id')
            ->setParameter('id', $exam);

        return $qb->getQuery()
            ->getResult();
    }
}
