portal_user_course:
    resource: "@PortalBundle/Controller/UserCourseController.php"
    type:     annotation

portal_user_exam:
    resource: "@PortalBundle/Controller/UserExamController.php"
    type:     annotation

portal_user_test:
    resource: "@PortalBundle/Controller/UserTestController.php"
    type:     annotation

portal_test_question:
    resource: "@PortalBundle/Controller/TestQuestionController.php"
    type:     annotation

portal_test:
    resource: "@PortalBundle/Controller/TestController.php"
    type:     annotation

portal_exam:
    resource: "@PortalBundle/Controller/ExamController.php"
    type:     annotation

portal_homework:
    resource: "@PortalBundle/Controller/HomeworkController.php"
    type:     annotation

portal_material:
    resource: "@PortalBundle/Controller/MaterialController.php"
    type:     annotation

portal_flow:
    resource: "@PortalBundle/Controller/FlowController.php"
    type:     annotation

portal_course:
    resource: "@PortalBundle/Controller/CourseController.php"
    type:     annotation

portal_news:
    resource: "@PortalBundle/Controller/NewsController.php"
    type:     annotation

portal_vacancy:
    resource: "@PortalBundle/Controller/VacancyController.php"
    type:     annotation

portal_company:
    resource: "@PortalBundle/Controller/CompanyController.php"
    type:     annotation

portal:
    resource: "@PortalBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
