portal_company:
    resource: "@PortalBundle/Controller/CompanyController.php"
    type:     annotation

portal:
    resource: "@PortalBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
