portal_homepage:
    path:     /
    defaults: { _controller: "PortalBundle:Index:index" }
    requirements:
         methods:  GET

portal_about:
    path:   /about
    defaults: { _controller: "PortalBundle:Index:about" }
    requirements:
         methods:  GET

registration_cases:
    path:   /reg-as
    defaults: { _controller: "PortalBundle:Registration:index" }
    requirements:
         methods:  GET

registration_company_reg:
    path:   /reg-company
    defaults: { _controller: "PortalBundle:Registration:register" }
