portal_homepage:
    path:     /
    defaults: { _controller: "PortalBundle:Index:index" }
    requirements:
         methods:  GET

portal_about:
    path:   /about
    defaults: { _controller: "PortalBundle:Index:about" }
    requirements:
         methods:  GET

teacher_profile:
    path:   /profile-teacher
    defaults: { _controller: "PortalBundle:Index:teacherProfile" }
    requirements:
         methods:  GET

portal_profile:
    path:   /profile-cases
    defaults: { _controller: "PortalBundle:Index:profile" }
    requirements:
         methods:  GET

registration_cases:
    path:   /reg-as
    defaults: { _controller: "PortalBundle:Registration:index" }
    requirements:
         methods:  GET

registration_company_reg:
    path:   /reg-company
    defaults: { _controller: "PortalBundle:Registration:register" }

invite_teacher:
    path:   /invite-teacher
    defaults: { _controller: "PortalBundle:Registration:inviteTeacher" }

confirm_registration:
    path:   /confirm-reg/{token}
    defaults: { _controller: "PortalBundle:Registration:confirmRegistration" }
