services:
#    portal.example:
#        class: ELearning\CompanyPortalBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
   company_reg_form:
      class: ELearning\CompanyPortalBundle\Form\CompanyRegistrationType
      tags:
         -  { name: form.type }