services:
#    portal.example:
#        class: ELearning\CompanyPortalBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
   company_reg_form:
      class: ELearning\CompanyPortalBundle\Form\CompanyRegistrationType
      tags:
         -  { name: form.type }

   portal_topic_chat:
      class: ELearning\CompanyPortalBundle\Topic\ChatTopic
      arguments:
         - @doctrine.orm.default_entity_manager
         - @gos_web_socket.websocket.client_manipulator
      tags:
         - { name: gos_web_socket.topic }